### PR TITLE
feat(menus): connect game with instructions and splash

### PR DESCRIPTION
**Pull request by viantirreau**
### Context
​
Adds more than a simple lorem ipsum to the instructions and connects the splash screen with the game scene.

#### What to check

Unstaged one file inside UserSettings that apparently was not captured by the `.gitignore` file. It should not affect your local settings, but maybe back them up just in case

### CODE REVIEW

**Comment by viantirreau** [comment]
[Instrucciones](https://trello.com/c/ONdjViqo/8-instrucciones)

**Comment by viantirreau** [comment]
[Conectar vistas para navegación](https://trello.com/c/HqqiRqpI/21-conectar-vistas-para-navegaci%C3%B3n)

**Review by barbaraim — APPROVED** [review]
Ojo despues con los anchors 😄

**Comment by barbaraim** [comment]
Y poner scripts en carpeta scripts

**Pull request merged**
